local   all             all                                     trust

hostssl all             all             0.0.0.0/0               md5
hostssl all             all             ::/0                    md5

host    all             all             0.0.0.0/0               reject
host    all             all             ::/0                    reject
