################################################################################
# Automatically-generated file. Do not edit!
################################################################################

ASM_SRCS := 
C++_SRCS := 
CC_SRCS := 
CPP_SRCS := 
CXX_SRCS := 
C_SRCS := 
C_UPPER_SRCS := 
OBJ_SRCS := 
O_SRCS := 
S_UPPER_SRCS := 
C++_DEPS := 
CC_DEPS := 
CPP_DEPS := 
CXX_DEPS := 
C_DEPS := 
C_UPPER_DEPS := 
EXECUTABLES := 
OBJS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
src \
src/actions \
src/amazon \
src/analyzer \
src/asynctask \
src/channeljsonconfig \
src/client \
src/client/call_handler \
src/conn \
src/conn/call_handler \
src/converter \
src/crypt_blowfish \
src/cyclictasks \
src/datalogger \
src/db \
src/device \
src/device/call_handler \
src/device/value \
src/distributedobjects \
src/google \
src/http \
src/ipc \
src/json \
src/mqtt \
src/push \
src/scene \
src/srpc \
src/test \
src/test/actions \
src/test/amazon \
src/test/analyzer \
src/test/asynctask \
src/test/channeljsonconfig \
src/test/client \
src/test/conn \
src/test/cyclictasks \
src/test/device \
src/test/device/value \
src/test/distributedobjects \
src/test/doubles \
src/test/doubles/actions \
src/test/doubles/amazon \
src/test/doubles/asynctask \
src/test/doubles/channeljsonconfig \
src/test/doubles/client \
src/test/doubles/conn \
src/test/doubles/cyclictasks \
src/test/doubles/db \
src/test/doubles/device \
src/test/doubles/distributedobjects \
src/test/doubles/google \
src/test/doubles/http \
src/test/doubles/integration/asynctask \
src/test/doubles/integration/mqtt \
src/test/doubles/ipc \
src/test/doubles/mqtt \
src/test/doubles/push \
src/test/doubles/scene \
src/test/doubles/webhook \
src/test/google \
src/test/http \
src/test/integration \
src/test/integration/amazon \
src/test/integration/client \
src/test/integration/cyclictasks \
src/test/integration/datalogger \
src/test/integration/google \
src/test/integration/mqtt \
src/test/integration/scene \
src/test/integration/webhook \
src/test/ipc \
src/test/mqtt \
src/test/push \
src/test/scene \
src/test/webhook \
src/user \
src/webhook \

