ifndef SSLDIR
SSLDIR=/usr/src/openssl
endif

ifndef CC
CC=gcc
endif

ifndef CXX
CXX=g++
endif

ifeq ($(CC), cc)
CC=gcc
endif

ifdef MARIADB
LIBMYSQL=mariadbclient
INCMYSQL=/usr/lib/mariadb
else
LIBMYSQL=mysqlclient
INCMYSQL=/usr/lib/mysql
endif

ifndef SSOCKET_WRITE_TO_FILE
SSOCKET_WRITE_TO_FILE=0
endif
