CREATE EXTENSION timescaledb;
CREATE TABLE supla_em_current_log (channel_id INT NOT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, phase_no SMALLINT NOT NULL, min NUMERIC(6, 3) NOT NULL, max NUMERIC(6, 3) NOT NULL, avg NUMERIC(6, 3) NOT NULL, PRIMARY KEY(channel_id, date, phase_no));
COMMENT ON COLUMN supla_em_current_log.date IS '(DC2Type:stringdatetime)';
COMMENT ON COLUMN supla_em_current_log.phase_no IS '(DC2Type:tinyint)';
SELECT create_hypertable('supla_em_current_log', 'date');
CREATE TABLE supla_em_log (channel_id INT NOT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, phase1_fae BIGINT DEFAULT NULL, phase1_rae BIGINT DEFAULT NULL, phase1_fre BIGINT DEFAULT NULL, phase1_rre BIGINT DEFAULT NULL, phase2_fae BIGINT DEFAULT NULL, phase2_rae BIGINT DEFAULT NULL, phase2_fre BIGINT DEFAULT NULL, phase2_rre BIGINT DEFAULT NULL, phase3_fae BIGINT DEFAULT NULL, phase3_rae BIGINT DEFAULT NULL, phase3_fre BIGINT DEFAULT NULL, phase3_rre BIGINT DEFAULT NULL, fae_balanced BIGINT DEFAULT NULL, rae_balanced BIGINT DEFAULT NULL, PRIMARY KEY(channel_id, date)); 
COMMENT ON COLUMN supla_em_log.date IS '(DC2Type:stringdatetime)'; 
SELECT create_hypertable('supla_em_log', 'date'); 
CREATE TABLE supla_em_power_active_log (channel_id INT NOT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, phase_no SMALLINT NOT NULL, min NUMERIC(11, 5) NOT NULL, max NUMERIC(11, 5) NOT NULL, avg NUMERIC(11, 5) NOT NULL, PRIMARY KEY(channel_id, date, phase_no)); 
COMMENT ON COLUMN supla_em_power_active_log.date IS '(DC2Type:stringdatetime)'; 
COMMENT ON COLUMN supla_em_power_active_log.phase_no IS '(DC2Type:tinyint)'; 
SELECT create_hypertable('supla_em_power_active_log', 'date'); 
CREATE TABLE supla_em_voltage_aberration_log (channel_id INT NOT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, phase_no SMALLINT NOT NULL, count_total INT NOT NULL, count_above INT NOT NULL, count_below INT NOT NULL, sec_above INT NOT NULL, sec_below INT NOT NULL, max_sec_above INT NOT NULL, max_sec_below INT NOT NULL, min_voltage NUMERIC(7, 2) NOT NULL, max_voltage NUMERIC(7, 2) NOT NULL, avg_voltage NUMERIC(7, 2) NOT NULL, measurement_time_sec INT NOT NULL, PRIMARY KEY(channel_id, date, phase_no)); 
COMMENT ON COLUMN supla_em_voltage_aberration_log.date IS '(DC2Type:stringdatetime)'; 
COMMENT ON COLUMN supla_em_voltage_aberration_log.phase_no IS '(DC2Type:tinyint)'; 
SELECT create_hypertable('supla_em_voltage_aberration_log', 'date'); 
CREATE TABLE supla_em_voltage_log (channel_id INT NOT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, phase_no SMALLINT NOT NULL, min NUMERIC(5, 2) NOT NULL, max NUMERIC(5, 2) NOT NULL, avg NUMERIC(5, 2) NOT NULL, PRIMARY KEY(channel_id, date, phase_no)); 
COMMENT ON COLUMN supla_em_voltage_log.date IS '(DC2Type:stringdatetime)'; 
COMMENT ON COLUMN supla_em_voltage_log.phase_no IS '(DC2Type:tinyint)'; 
SELECT create_hypertable('supla_em_voltage_log', 'date'); 
CREATE TABLE supla_gp_measurement_log (channel_id INT NOT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, open_value DOUBLE PRECISION NOT NULL, close_value DOUBLE PRECISION NOT NULL, avg_value DOUBLE PRECISION NOT NULL, max_value DOUBLE PRECISION NOT NULL, min_value DOUBLE PRECISION NOT NULL, PRIMARY KEY(channel_id, date)); 
COMMENT ON COLUMN supla_gp_measurement_log.date IS '(DC2Type:stringdatetime)'; 
SELECT create_hypertable('supla_gp_measurement_log', 'date'); 
CREATE TABLE supla_gp_meter_log (channel_id INT NOT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, value DOUBLE PRECISION NOT NULL, PRIMARY KEY(channel_id, date)); 
COMMENT ON COLUMN supla_gp_meter_log.date IS '(DC2Type:stringdatetime)'; 
SELECT create_hypertable('supla_gp_meter_log', 'date'); 
CREATE TABLE supla_ic_log (channel_id INT NOT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, counter BIGINT NOT NULL, calculated_value BIGINT NOT NULL, PRIMARY KEY(channel_id, date)); 
COMMENT ON COLUMN supla_ic_log.date IS '(DC2Type:stringdatetime)'; 
SELECT create_hypertable('supla_ic_log', 'date'); 
CREATE TABLE supla_temperature_log (channel_id INT NOT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, temperature NUMERIC(8, 4) NOT NULL, PRIMARY KEY(channel_id, date)); 
COMMENT ON COLUMN supla_temperature_log.date IS '(DC2Type:stringdatetime)'; 
SELECT create_hypertable('supla_temperature_log', 'date'); 
CREATE TABLE supla_temphumidity_log (channel_id INT NOT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, temperature NUMERIC(8, 4) NOT NULL, humidity NUMERIC(8, 4) NOT NULL, PRIMARY KEY(channel_id, date)); 
COMMENT ON COLUMN supla_temphumidity_log.date IS '(DC2Type:stringdatetime)'; 
SELECT create_hypertable('supla_temphumidity_log', 'date'); 
CREATE TABLE supla_thermostat_log (channel_id INT NOT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, "on" BOOLEAN NOT NULL, measured_temperature NUMERIC(5, 2) NOT NULL, preset_temperature NUMERIC(5, 2) NOT NULL, PRIMARY KEY(channel_id, date)); 
COMMENT ON COLUMN supla_thermostat_log.date IS '(DC2Type:stringdatetime)'; 
SELECT create_hypertable('supla_thermostat_log', 'date');
CREATE TABLE supla_energy_price_log (date_from TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_to TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, rce NUMERIC(8, 4) DEFAULT NULL, fixing1 NUMERIC(8, 4) DEFAULT NULL, fixing2 NUMERIC(8, 4) DEFAULT NULL, PRIMARY KEY(date_from));
COMMENT ON COLUMN supla_energy_price_log.date_from IS '(DC2Type:stringdatetime)';
COMMENT ON COLUMN supla_energy_price_log.date_to IS '(DC2Type:stringdatetime)';
SELECT create_hypertable('supla_energy_price_log', 'date_from');
ALTER TABLE supla_energy_price_log ADD pdgsz SMALLINT DEFAULT NULL;
COMMENT ON COLUMN supla_energy_price_log.pdgsz IS '(DC2Type:tinyint)';
